### ISSUE TITLE
"module SFTPClient is not available" (related to the issue: add :sftp_client to "application" in the mix.exs file ?)

### ISSUE THREAD

**Issue by jipen** [i22-digitalagentur/sftp_client#6] opened 2019-09-02 13:07 UTC
Found it !
That happens when I make and run a prod release (Elixir 1.9.0):
set MIX_ENV=prod mix release
then myprogram start
then when I try a command (myprogram rpc "mycommand(args)":
=> crash and
** (UndefinedFunctionError) function SFTPClient.connect/1 is undefined (module SFTPClient is not available)
When I had :sftp_client to applications or extra_applications options in mix.exs, everything is OK.
Did I forget something when I made the release ?
That doesn't happen with iex -S mix (and yes,  the config files have the same content: dev.exs == releases.exs ;) )

[Edit] Seems to be a common issue : [Here](https://stackoverflow.com/questions/47629659/module-not-available-in-release) and [here](https://github.com/bitwalker/toml-elixir/issues/15)

**Comment by tlux** [comment] 2019-09-02 13:24
What does your `mycommand` call exactly do?

For the `rpc` and `eval` commands you need to ensure the application is loaded and started before using any modules from it (`Application.ensure_all_started(:sftp_client)`). AFAIK, those commands do not start any apps at all. So this is expected behavior.

Thus, it is a common practice to have a `YourApp.ReleaseTasks` module that contains all your release specific tasks, such as database migrations and that starts up all apps as needed. By the way, usage in releasing is one of the reasons why `Ecto.Migrator.with_repo/2` has been introduced in Ecto; it starts the ecto app (among other things) before performing any database operations.

For example, this is the release task we use in one of our apps for migrating Ecto repos:

```elixir 
defmodule MyApp.ReleaseTasks do
  @additional_startup_apps [
    :crypto,
    :httpoison
  ]

  def migrate do
    Application.load(:my_app)
    Enum.each(@additional_startup_apps, &Application.ensure_all_started/1)

    Migrator.with_repo(Repo, fn _repo ->
      # ...
    end)
  end
end
```

Did you do it like that?

**Comment by jipen** [comment] 2019-09-02 13:36
"mycommand" only call SFTPClient.connect and no, I wasn't aware of that ReleaseTasks thing as all the others deps  (:elixir_uuid, logger, :ssh, :logger_file_backend) are already in my applications or extra_applications options...
I will give a try.

**Comment by tlux** [comment] 2019-09-02 13:38
It's also described in the official mix release docs :)

https://hexdocs.pm/mix/Mix.Tasks.Release.html (Section "Helper module")

**Comment by jipen** [comment] 2019-09-02 13:40
Sorry to be such an ignorant... ;)

**Comment by jipen** [comment] 2019-09-02 13:58
OMG: I read the docs and (if I understood well) I should wrap each function I want to call by rpc with this "Application.load(:my_app)
    Enum.each(@additional_startup_apps, &Application.ensure_all_started/1)" stuff ?!?
For the moment, I have already 14 commands/functions for my file transfers !
Then I prefer to simply add :sftp_client to my extra_applications options which works nice with release and iex -S mix as well.
NB: I launch my rpc commands AFTER having started MyApp ("MyApp start") so it's a bit odd to be required to verify that each deps modules is loaded for each rpc call. These modules should already be loaded when the app (and then its deps) is started !

**Comment by tlux** [comment] 2019-09-02 14:04
I think the releasing stuff has not yet grown up; it's just the first iteration. But for the moment that seems to be the way to go. 

TBH, I'm quite surprised that it works when you add sftp_client to extra_applications as rpc/eval should not even start YOUR app. 😉

**Comment by tlux** [comment] 2019-09-02 17:35
I close the issue for now, as this is not really a bug.

**Closed as completed by tlux** 2019-09-02 17:35 UTC
